AdminLTE1/Models/CMS.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AdminLTE1.Models
{
    public class CMS
    {
        public int Id { get; set; }

        [Required]
        [Remote("PageAlreadyExist", "Home",/* AdditionalFields = "Id",*/ ErrorMessage = "Page name already exists")]
        public string PageName { get; set; }

        [Required]
        [Remote("URLAlreadyExist", "Home", ErrorMessage = "Page URL already exists")]
        public string PageURL { get; set; }

        public string Description { get; set; }
        public string BannerImage { get; set; }

        [NotMapped]
        [Required]
        public IFormFile BannerImageFile { get; set; }

    }
}

AdminLTE1/Controllers/CMSController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AdminLTE1.Data;
using AdminLTE1.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace AdminLTE1.Controllers
{
    public class CMSController : Controller
    {
        private readonly AppDbContext _context;        private readonly IHostingEnvironment _hostEnvironment;

        public CMSController(AppDbContext context, IHostingEnvironment hostEnvironment)        {            _context = context;            _hostEnvironment = hostEnvironment;        }

        public IActionResult Index()        {

            List<CMS> lstmodel = new List<CMS>();            var models = _context.CMS;            foreach (var item in models)            {                CMS mvm = new CMS();                mvm.Id = item.Id;                mvm.PageName = item.PageName;                mvm.PageURL = item.PageURL;                mvm.Description = item.Description;                mvm.BannerImage = item.BannerImage;                lstmodel.Add(mvm);            }

            return View(lstmodel);        }        [HttpGet]        public IActionResult CreatePage()        {            return View();        }        [HttpPost]        public IActionResult CreatePage(CMS model)        {            if (model != null)            {                var cmsModel = new CMS();                cmsModel.PageName = model.PageName;                cmsModel.PageURL = model.PageURL;                cmsModel.Description = model.Description;




                if (model.BannerImageFile!= null)                {                    string wwwRootPath = _hostEnvironment.WebRootPath;                    string fileName = Path.GetFileNameWithoutExtension(model.BannerImageFile.FileName);                    string extension = Path.GetExtension(model.BannerImageFile.FileName);                    cmsModel.BannerImage = DateTime.Now.ToString("yymmssfff") + extension;                    string path = Path.Combine(wwwRootPath, "CMSImages", cmsModel.BannerImage);
                    var fileStream = new FileStream(path, FileMode.Create);                    model.BannerImageFile.CopyTo(fileStream);                }
                _context.CMS.Add(cmsModel);                _context.SaveChanges();                return RedirectToAction("Index");            }                       return View();        }        [HttpGet]        public IActionResult EditPage(int id)        {            CMS mvm = new CMS();            var page = _context.CMS.FirstOrDefault(m => m.Id == id);            if (page != null)            {                mvm.PageName = page.PageName;                mvm.PageURL = page.PageURL;                mvm.Description = page.Description;                mvm.BannerImage = page.BannerImage;            }            return View(mvm);        }        [HttpPost]        public IActionResult EditPage(CMS model)        {            if (model != null)            {                var PageItem = _context.CMS.FirstOrDefault(m => m.Id == model.Id);                if (PageItem != null)                {                    PageItem.PageName = model.PageName;                    PageItem.PageURL = model.PageURL;                    PageItem.Description = model.Description;                    var BannerImage = PageItem.BannerImage;                    if (model.BannerImageFile != null)                    {                        if (BannerImage != model.BannerImage)                        {                            string wwwRootPath = _hostEnvironment.WebRootPath;                            string fileName = Path.GetFileNameWithoutExtension(model.BannerImageFile.FileName);                            string extension = Path.GetExtension(model.BannerImageFile.FileName);                            PageItem.BannerImage = DateTime.Now.ToString("yymmssfff") + extension;                            string path = Path.Combine(wwwRootPath, "CMSImages", PageItem.BannerImage);
                            //var mem = new MemoryStream();
                            //user.ProfilePicture
                            var fileStream = new FileStream(path, FileMode.Create);                            model.BannerImageFile.CopyTo(fileStream);                        }                        else if (BannerImage == null)                        {                            string wwwRootPath = _hostEnvironment.WebRootPath;                            string fileName = Path.GetFileNameWithoutExtension(model.BannerImageFile.FileName);                            string extension = Path.GetExtension(model.BannerImageFile.FileName);                            PageItem.BannerImage = DateTime.Now.ToString("yymmssfff") + extension;                            string path = Path.Combine(wwwRootPath, "CMSImages", PageItem.BannerImage);
                            //var mem = new MemoryStream();
                            //user.ProfilePicture
                            var fileStream = new FileStream(path, FileMode.Create);                            model.BannerImageFile.CopyTo(fileStream);                        }                    }                    _context.Entry(PageItem).State = Microsoft.EntityFrameworkCore.EntityState.Modified;                    _context.SaveChanges();                    return RedirectToAction("Index");                }                return View();            }            return View();        }                public IActionResult DeletePage(int id)        {            var page = _context.CMS.FirstOrDefault(m => m.Id == id);            _context.CMS.Remove(page);            _context.SaveChanges();            TempData["successMessage"] = "Page Deleted Successfully.";            TempData.Keep();            return RedirectToAction("Index");        }

    }
}


AdminLTE1/Views/CMS/CreatePage.cshtml
@model AdminLTE1.Models.CMS
@{
    ViewData["Title"] = "CreatePage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/ckeditor/ckeditor.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

@*<environment include="Development">
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>*@

<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create Page</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="PageName"></label>
                        <input asp-for="PageName" class="form-control" placeholder="Name">
                        <span asp-validation-for="PageName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PageURL"></label>
                        <input asp-for="PageURL" class="form-control" placeholder="URL">
                        <span asp-validation-for="PageURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <textarea id="Description" class="ckeditor" name="Description" rows="200"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BannerImageFile"></label>
                        <input asp-for="BannerImageFile" class="form-control" type="file" />
                        <span asp-validation-for="BannerImageFile" class="text-danger"></span>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

AdminLTE1/Views/CMS/EditPage.cshtml
@model AdminLTE1.Models.CMS
@{
    ViewData["Title"] = "EditPage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/ckeditor/ckeditor.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<div class="row">
    <!-- left column -->
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Edit Page</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="PageName"></label>
                        <input asp-for="PageName" class="form-control">
                        <span asp-validation-for="PageName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PageURL"></label>
                        <input asp-for="PageURL" class="form-control">
                        <span asp-validation-for="PageURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">

                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" id="Description" class="ckeditor" name="Description" rows="200"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BannerImageFile"></label>
                        @if (Model.BannerImage != null)
                        {
                            <img width="50px" style="width:50px;height:50px; object-fit:cover" src="~/CMSImages/@Model.BannerImage">
                        }
                        <input asp-for="BannerImageFile" class="form-control" type="file" />
                        <span asp-validation-for="BannerImageFile" class="text-danger"></span>
                    </div>
                
                <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="submit" asp-controller="CMS" asp-action="Index" class="btn btn-primary">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
@*@section scripts{

        <script>
            $(document).ready(function () {

                //CKEDITOR.replace('#Description');

            }
            )
        </script>
    }*@

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

AdminLTE1/Views/CMS/Index.cshtml
@model IEnumerable<AdminLTE1.Models.CMS>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/ckeditor/ckeditor.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<h1>Manage Pages</h1>

<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <a class="btn btn-primary" style="width:auto" asp-controller="CMS" asp-action="CreatePage">Create Page</a>
        </div>

            <table class="table table-striped" id="MyDataTable">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Page Name</th>
                        <th>Page Url</th>
                        <th>Description</th>
                        <th>Banner Image</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var cms in Model)
                    {
                        <tr>
                            <td>@cms.Id</td>
                            <td>@cms.PageName</td>
                            <td>@cms.PageURL</td>
                            <td>@cms.Description</td>
                            <td>
                                @if (cms.BannerImage != null)
                                {
                                    <img style="width:70px;height:70px; object-fit:cover" src="~/CMSImages/@cms.BannerImage">
                                }
                            </td>
                            <td>
                                <a asp-action="EditPage" asp-controller="CMS" asp-route-id="@cms.Id" class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                <a asp-action="DeletePage" asp-controller="CMS" asp-route-id="@cms.Id" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete page : @cms.PageName')">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
    </div>
</div>


@section scripts{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.css" />
    <script src="~/js/CustomScript.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#MyDataTable").DataTable();
            CKEDITOR.replace('#Description');

        }
        )
    </script>
}