AdminLTE1/ViewModels/PermissionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AdminLTE1.ViewModels
{
    public class PermissionViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public int ParentId { get; set; }
        public int MenuLevel { get; set; }
        public bool HasAccess { get; set; }
        public int MenuGrpId { get; set; }
    }
}

AdminLTE1/Controllers/PermissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AdminLTE1.Entities;
using AdminLTE1.Helper;
using AdminLTE1.Models;
using AdminLTE1.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AdminLTE1.Controllers
{
    [AuthorizeActionFilter]
    public class PermissionController : Controller
    {
        private readonly AppDbContext _context;
        public PermissionController(AppDbContext context)
        {
            this._context = context;
        }


        public IActionResult Index()        {            var role = (from r in _context.Roles                        join per in _context.MenuPermissions                        on r.Id equals Convert.ToString(per.RoleId)                        select new EditRoleViewModel                        {                            RoleName = r.Name,                            RoleId = r.Id                        }).GroupBy(n => new { n.RoleId, n.RoleName }).Select(g => g.FirstOrDefault()).ToList();


            return View(role);        }


        [HttpGet]
        public IActionResult CreatePermission(Guid RoleId)
        {
            List<PermissionViewModel> lstPermission = new List<PermissionViewModel>();

            var result = (from Menus in _context.MenuItems
                          join Permissions in _context.MenuPermissions.Where(r => r.RoleId == RoleId)
                          on Menus.Id equals Permissions.MenuId into menuPerm
                          from perm in menuPerm.DefaultIfEmpty()
                          select new PermissionViewModel
                          {
                              Id = Menus.Id,
                              Path = Menus.Path,
                              Name = Menus.Name,
                              ParentId = Menus.ParentId,
                              MenuLevel = Menus.MenuLevel,
                              HasAccess = perm == null ? false : !(string.IsNullOrEmpty(Convert.ToString(perm.RoleId)))
                          }).ToList();

            var RolesList = (from roles in _context.Roles
                             select new SelectListItem
                             {
                                 Value = roles.Id,
                                 Text = roles.Name
                             }).ToList();
            ViewBag.RolesList = RolesList;
            return View(result);
        }


        [HttpPost]
        public JsonResult CreatePermission([FromBody]UpdatePermissionViewModel[] model)
        {

            if (model != null)
            {

                var existing = _context.MenuPermissions.Where(R => R.RoleId == model.FirstOrDefault().RoleId).ToList();
                if (existing != null && existing.Count() > 0)

                {
                    return Json("Permission already assigned!");

                }

                else
                {
                    foreach (var item in model)
                    {
                        MenuPermission mnp = new MenuPermission();
                        mnp.MenuId = item.MenuId;
                        mnp.PermissionId = Guid.NewGuid();
                        mnp.RoleId = item.RoleId;
                        _context.MenuPermissions.Add(mnp);

                        _context.SaveChanges();
                    }


                    return Json("Saved Successfully!");
                }


            }
            return Json("NoData");

        }




        [HttpGet]
        public IActionResult EditPermission(Guid RoleId)
        {
            ViewBag.RoleId = RoleId;
            List<PermissionViewModel> lstPermission = new List<PermissionViewModel>();

            var result = (from Menus in _context.MenuItems
                          join Permissions in _context.MenuPermissions.Where(r => r.RoleId == RoleId)
                          on Menus.Id equals Permissions.MenuId into menuPerm
                          from perm in menuPerm.DefaultIfEmpty()
                          select new PermissionViewModel
                          {
                              Id = Menus.Id,
                              Path = Menus.Path,
                              Name = Menus.Name,
                              ParentId = Menus.ParentId,
                              MenuLevel = Menus.MenuLevel,
                              HasAccess = perm == null ? false : !(string.IsNullOrEmpty(Convert.ToString(perm.RoleId)))
                          }).ToList();

            return View(result);
        }

        [HttpPost]
        public JsonResult EditPermission([FromBody]UpdatePermissionViewModel[] model)
        {

            if (model != null)
            {

                int count = 0;
                foreach (var item in model)
                {
                    if (count == 0)
                    {
                        var existing = _context.MenuPermissions.Where(R => R.RoleId == item.RoleId);

                        foreach (var roles in existing)
                        {
                            _context.MenuPermissions.Remove(roles);
                        }
                        count++;
                    }
                    MenuPermission mnp = new MenuPermission();
                    mnp.MenuId = item.MenuId;
                    mnp.PermissionId = Guid.NewGuid();
                    mnp.RoleId = item.RoleId;
                    _context.MenuPermissions.Add(mnp);
                }

                _context.SaveChanges();

                return Json("Saved Successfully!");
            }
            return Json("NoData");
        }



                public IActionResult ViewPermission(Guid RoleId)        {            List<PermissionViewModel> lstPermission = new List<PermissionViewModel>();            var result = (from Menus in _context.MenuItems                          join Permissions in _context.MenuPermissions.Where(r => r.RoleId == RoleId)                          on Menus.Id equals Permissions.MenuId into menuPerm                          from perm in menuPerm.DefaultIfEmpty()                          select new PermissionViewModel                          {                              Id = Menus.Id,                              Path = Menus.Path,                              Name = Menus.Name,                              ParentId = Menus.ParentId,                              MenuLevel = Menus.MenuLevel,                              HasAccess = perm == null ? false : !(string.IsNullOrEmpty(Convert.ToString(perm.RoleId)))                          }).ToList();            var RolesList = (from roles in _context.Roles                             select new SelectListItem                             {                                 Value = roles.Id,                                 Text = roles.Name                             }).ToList();            ViewBag.RolesList = RolesList;            return View(result);        }








        [HttpGet]        public IActionResult DeletePermission(Guid RoleId)        {            var permission = _context.MenuPermissions.Where(m => m.RoleId == RoleId);            foreach (var perm in permission)            {                _context.MenuPermissions.Remove(perm);            }            var perms = _context.MenuPermissions.FirstOrDefault(m => m.RoleId == RoleId);            _context.MenuPermissions.Remove(perms);            _context.SaveChanges();            TempData["successMessage"] = "Permissions Deleted Successfully.";            TempData.Keep();            return RedirectToAction("Index");        }






        public IActionResult GetMenus()
        {
            List<MenuViewModel> lstmodel = new List<MenuViewModel>();
            var models = _context.MenuItems;

            foreach (var item in models)
            {
                MenuViewModel mvm = new MenuViewModel();
                mvm.Id = item.Id;
                mvm.Name = item.Name;
                mvm.Path = item.Path;
                mvm.ParentId = item.ParentId;
                mvm.MenuLevel = item.MenuLevel;
                mvm.MenuGrpId = item.MenuGrpId;

                lstmodel.Add(mvm);
            }

            ViewBag.successMessage = TempData["successMessage"];
            return View(lstmodel);
        }


        [HttpGet]
        public IActionResult CreateMenu()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateMenu(MenuViewModel model)
        {
            if (model != null)
            {
                var menuModel = new MenuItem();
                menuModel.Name = model.Name;
                menuModel.Path = model.Path;
                menuModel.ParentId = model.ParentId;
                menuModel.MenuLevel = model.MenuLevel;
                menuModel.MenuGrpId = model.MenuGrpId;

                _context.MenuItems.Add(menuModel);
                _context.SaveChanges();

                return RedirectToAction("GetMenus");
            }
            return View();
        }

        [HttpGet]
        public IActionResult EditMenu(int Id)
        {
            MenuViewModel mvm = new MenuViewModel();
            var menu = _context.MenuItems.FirstOrDefault(m => m.Id == Id);

            if (menu != null)
            {
                mvm.Id = menu.Id;
                mvm.Name = menu.Name;
                mvm.Path = menu.Path;
                mvm.ParentId = menu.ParentId;
                mvm.MenuLevel = menu.MenuLevel;
                mvm.MenuGrpId = menu.MenuGrpId;
            }
            return View(mvm);
        }

        [HttpGet]
        public IActionResult DeleteMenu(int Id)
        {

AdminLTE1/Views/Permission/CreateMenu.cshtml
@model AdminLTE1.ViewModels.MenuViewModel
@{
    ViewBag.Title = "Create Menu";
}
<div class="row">
   
    <div class="col-md-6">
        
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create Menu</h3>
            </div>
           
            <form method="post">
                <div class="card-body">
                    <div asp-validation-summary="All" class="text-danger">
                    </div>
                    <div class="form-group">
                        <input asp-for="Id" hidden class="form-control">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" placeholder="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Path"></label>
                        <input asp-for="Path" class="form-control" placeholder="Path">
                        <span asp-validation-for="Path" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ParentId"></label>
                        <input asp-for="ParentId" class="form-control" placeholder="ParentId">
                        <span asp-validation-for="ParentId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MenuLevel"></label>
                        <input asp-for="MenuLevel" class="form-control" placeholder="MenuLevel">
                        <span asp-validation-for="MenuLevel" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MenuGrpId"></label>
                        <input asp-for="MenuGrpId" class="form-control" placeholder="MenuGrpId">
                        <span asp-validation-for="MenuGrpId" class="text-danger"></span>
                    </div>
                </div>
              
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

AdminLTE1/Views/Permission/CreatePermission.cshtml
@model IEnumerable<AdminLTE1.ViewModels.PermissionViewModel>
@{
    ViewBag.Title = "Create Permission";
}
@if (Model.Any())
{
    <div class="col-md-12">
        <div class="card">

            <div class="card-header">
                <label>Role</label>
                @Html.DropDownList("RoleId", (IEnumerable<SelectListItem>)ViewBag.RolesList, "Select Role")

                <button id="btnSave" class="btn btn-primary fa-pull-right">Save</button>
            </div>
            <div class="card-body p-0">
                <table id="idgrid" class="table">
                    <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Permission Id</th>
                            <th>Name</th>
                            <th>Path</th>
                            <th>ParentId</th>
                            <th>MenuLevel</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var menu in Model)
                        {
                            <tr>
                                <td><input type="checkbox" value="@menu.Id"/></td>
                                <td>@menu.Id</td>
                                <td>@menu.Name</td>
                                <td>@menu.Path</td>
                                <td>@menu.ParentId</td>
                                <td>@menu.MenuLevel</td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>

    </div>
}


<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
<script>

    $(document).ready(function () {


        $("#btnSave").on('click', function (e) {
            var RoleId = $('#RoleId').val();

            var arr = [];
            $('#idgrid').find('input[type="checkbox"]:checked').each(function () {

                requestData = {
                    MenuId: this.value,
                    RoleId: RoleId
                }
                arr.push(requestData);
            });


            //debugger;
            $.ajax({
                url: '/Permission/CreatePermission',
                type: 'POST',
                data: JSON.stringify(arr),
                dataType: 'json',
                contentType: 'application/json',
                error: function (xhr) {
                    alert('Error: ' + xhr.statusText);
                },
                success: function (result) {
                    alert(result);
                },

            });

        });
    });
</script>

@section scripts{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.css" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#MyDataTable").DataTable();
        }
        )
    </script>
}

AdminLTE1/Views/Permission/EditMenu.cshtml
@model AdminLTE1.ViewModels.MenuViewModel
@{
    ViewBag.Title = "Edit Menu";
}
<div class="row">
   
    <div class="col-md-6">
       
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Edit Menu</h3>
            </div>
           
            <form method="post">
                <div class="card-body">
                    <div asp-validation-summary="All" class="text-danger">
                    </div>
                    <div class="form-group">
                        <input asp-for="Id" hidden class="form-control">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" placeholder="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Path"></label>
                        <input asp-for="Path" class="form-control" placeholder="Path">
                        <span asp-validation-for="Path" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ParentId"></label>
                        <input asp-for="ParentId" class="form-control" placeholder="ParentId">
                        <span asp-validation-for="ParentId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MenuLevel"></label>
                        <input asp-for="MenuLevel" class="form-control" placeholder="MenuLevel">
                        <span asp-validation-for="MenuLevel" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MenuGrpId"></label>
                        <input asp-for="MenuGrpId" class="form-control" placeholder="MenuGrpId">
                        <span asp-validation-for="MenuGrpId" class="text-danger"></span>
                    </div>
                </div>
               
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

AdminLTE1/Views/Permission/GetMenus.cshtml
@model IEnumerable<AdminLTE1.ViewModels.MenuViewModel>
@{
    ViewBag.Title = "All Menu";
}
@if (ViewBag.successMessage != null)
{
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> @ViewBag.successMessage
    </div>
}
@if (Model.Any())
{
    <div class="col-md-12">
        <div class="card">
           
            <div class="card-header">
                <a class="btn btn-primary" style="width:auto"
                   asp-controller="Permission" asp-action="CreateMenu">
                    Create Menu
                </a>
            </div>
            <div class="card-body p-0">
                <table class="table">
                    <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Name</th>
                            <th>Path</th>
                            <th>ParentId</th>
                            <th>MenuLevel</th>
                            <th>MenuGrpId</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var menu in Model)
                        {
                            <tr>
                                <td>@menu.Id</td>
                                <td>@menu.Name</td>
                                <td>@menu.Path</td>
                                <td>@menu.ParentId</td>
                                <td>@menu.MenuLevel</td>
                                <td>@menu.MenuGrpId</td>
                                <td><a href="@Url.Action("EditMenu","Permission",new { Id=menu.Id})" class="btn btn-primary">Edit</a></td>
                                <td><a href="@Url.Action("DeleteMenu","Permission",new {Id=menu.Id})" class="btn btn-danger">Delete</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        
        </div>
       
    </div>
}
else
{
    <div class="card">
        <div class="card-header">
            No menu created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a menu
            </h5>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" style="width:auto"
               asp-controller="Permission" asp-action="CreateMenu">
                Create Menu
            </a>
        </div>
    </div>
}

AdminLTE1/Views/Permission/GetPermissions.cshtml
@model IEnumerable<AdminLTE1.ViewModels.PermissionViewModel>
@{
    ViewBag.Title = "Menu Permission";
}
@if (Model.Any())
{
    <div class="col-md-12">
        <div class="card">
          
            <div class="card-header">
                <label>Role</label>
                @Html.DropDownList("RoleId", (IEnumerable<SelectListItem>)ViewBag.RolesList,"Select Role")

                <button id="btnSave" class="btn btn-primary fa-pull-right">Save</button>
            </div>
            <div class="card-body p-0">
                <table id="idgrid" class="table">
                    <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Permission Id</th>
                            <th>Name</th>
                            <th>Path</th>
                            <th>ParentId</th>
                            <th>MenuLevel</th>
                         
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var menu in Model)
                        {
                            <tr>
                                <td><input type="checkbox" value="@menu.Id" checked="@menu.HasAccess" /></td>
                                <td>@menu.Id</td>
                                <td>@menu.Name</td>
                                <td>@menu.Path</td>
                                <td>@menu.ParentId</td>
                                <td>@menu.MenuLevel</td>
                              
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
           
        </div>
    
    </div>
}
else
{
    <div class="card">
        <div class="card-header">
            No menu created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a menu
            </h5>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" style="width:auto"
               asp-controller="Permission" asp-action="CreateMenu">
                Create Menu
            </a>
        </div>
    </div>
}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
<script>

    $(document).ready(function () {

       $("#RoleId").on("change", function () {
            var selectedId = $(this).val();
            window.location.href = '@Url.Action("GetPermissions", "Permissions")' + '?RoleId=' + selectedId;
        });


        $("#btnSave").on('click', function (e) {
            var RoleId = $('#RoleId').val();
            var arr = [];
            $('#idgrid').find('input[type="checkbox"]:checked').each(function () {
                
                requestData= {
                    MenuId: this.value,
                    RoleId: RoleId
                }
                arr.push(requestData);
            });

            //debugger;
            $.ajax({
                url: '/Permission/UpdatePermission',
                type: 'POST',
                data: JSON.stringify(arr),
               dataType: 'json',
               contentType: 'application/json',
               error: function (xhr) {
                    alert('Error: ' + xhr.statusText);
                },
                success: function (result) {
                    alert(result);
                },
              
            });

        });
    });
</script>

@section scripts{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.css" />

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#MyDataTable").DataTable();
        }
        )
    </script>
}

AdminLTE1/Views/Permission/Index.cshtml
@model IEnumerable<AdminLTE1.ViewModels.EditRoleViewModel>
    @{
        ViewData["Title"] = "Index";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }


<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <a class="btn btn-primary" style="width:auto" asp-controller="Permission" asp-action="CreatePermission">Create Permission</a>
        </div>

        <table class="table" id="MyDataTable">
            <thead>
                <tr>
                    <th>Serial No</th>
                    <th>RoleName</th>
                    <th>Edit</th>
                    <th>Delete</th>
                    <th>View</th>

                </tr>
            </thead>
            <tbody>

                @{int count = 1;}
                @foreach (var role in Model)
                {

                    <tr>
                        <td>@count</td>
                        <td>@role.RoleName</td>
                        <td><a asp-action="EditPermission" asp-controller="Permission" asp-route-RoleId="@role.RoleId" class="btn btn-primary">Edit</a></td>
                        <td><a asp-action="DeletePermission" asp-controller="Permission" asp-route-RoleId="@role.RoleId" class="btn btn-primary">Delete</a></td>
                        <td><a asp-action="ViewPermission" asp-controller="Permission" asp-route-RoleId="@role.RoleId" class="btn btn-primary">View</a></td>
                    </tr>
                    count++;
                }
            </tbody>
        </table>
        </div>
    </div>
        @section scripts{
            <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.css" />

            <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.25/af-2.3.7/datatables.min.js"></script>

            <script>
                $(document).ready(function () {
                    $("#MyDataTable").DataTable();
                }
                )
            </script>
        }

AdminLTE1/Views/Permission/ListMenu.cshtml
@model IEnumerable<AdminLTE1.ViewModels.MenuViewModel>
@{
    ViewBag.Title = "All Menu";
}
@if (ViewBag.successMessage != null)
{
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> @ViewBag.successMessage
    </div>
}
@if (Model.Any())
{
  
            <div class="card-body p-0">
                <table class="table">
                    <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Name</th>
                            <th>Path</th>
                            <th>ParentId</th>
                            <th>MenuLevel</th>
                            <th>MenuGrpId</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var menu in Model)
                        {
                            <tr>
                                <td>@menu.Id</td>
                                <td>@menu.Name</td>
                                <td>@menu.Path</td>
                                <td>@menu.ParentId</td>
                                <td>@menu.MenuLevel</td>
                                <td>@menu.MenuGrpId</td>
                                <td><a href="@Url.Action("EditMenu","Permission",new { Id=menu.Id})" class="btn btn-primary">Edit</a></td>
                                <td><a href="@Url.Action("DeleteMenu","Permission",new {Id=menu.Id})" class="btn btn-danger">Delete</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

    


}
else
{
    <div class="card">
        <div class="card-header">
            No menu created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a menu
            </h5>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" style="width:auto"
               asp-controller="Permission" asp-action="CreateMenu">
                Create Menu
            </a>
        </div>
    </div>
}

AdminLTE1/Views/Permission/ViewPermission.cshtml
@model IEnumerable<AdminLTE1.ViewModels.PermissionViewModel>
@{
    ViewData["Title"] = "View Permissions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Model.Any())
{
    <div class="col-md-12">
        <div class="card">

            <div class="card-body p-0">
                <table id="idgrid" class="table">
                    <thead>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Permission Id</th>
                            <th>Name</th>
                            <th>Path</th>
                            <th>ParentId</th>
                            <th>MenuLevel</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var menu in Model)
                        {
                            <tr>
                                <td><input type="checkbox" disabled value="@menu.Id" checked="@menu.HasAccess" /></td>
                                <td>@menu.Id</td>
                                <td>@menu.Name</td>
                                <td>@menu.Path</td>
                                <td>@menu.ParentId</td>
                                <td>@menu.MenuLevel</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
          
        </div>
    </div>
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>